experiment_name: 02_SegFormer_Official_Context
use_boundary_head: false
use_context_head: true
use_class_weight: true
class_weight_method: median_frequency

loss_weight:
  segmentation: 1.0
  context: 0.3
boundary_loss_weight: 0.3
context_loss_weight: 0.3

epochs: 50
batch_size: 4
lr: 0.00006
weight_decay: 0.01
image_size: 512
num_workers: 4
pretrained_model_name: nvidia/segformer-b1-finetuned-ade-512-512
seed: 42
deterministic: true

augmentation:
  scale_range: [0.75, 1.50]
  hflip_prob: 0.5
  random_crop: true
  random_scale: true
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]

voc_root: ./VOCdevkit/VOC2012
train_txt: ./pbl_train.txt
val_txt: ./pbl_val.txt
output_dir: ./runs
